### ISSUE TITLE
[5/1 ~ 5/8] TODO

### ISSUE THREAD

**Issue by jinsoo335** [HeoManBo/SSUNOVEL#3]
- [ ] 회원 수정, 탈퇴 api 개발

- [ ] 보관함 관련 api 개발

- [ ] 배포 방식 찾기

- [ ] 리디 북스 크롤링 시작
