### ISSUE TITLE
[5/1~5/8] TODO

### ISSUE THREAD

**Issue by HeoManBo** [HeoManBo/SSUNOVEL#4]
- [ ]  DB 수정 (platform table -> novel table 병합, 완결 여부, 카테고리 추가
- [ ]  카카오 페이지 웹 소설 크롤링
- [ ]  소설 검색 API 설계
