### ISSUE TITLE
[TODO] 5/15-5/22

### ISSUE THREAD

**Issue by HeoManBo** [HeoManBo/SSUNOVEL#6]
- [x] 소설 DB 삽입시 파싱하는 코드 작성 

- [x] 메인페이지 작성 (download_cnt) 기준으로 내림차순 20개 

- [x] 소설 목록 조회 수정
1. 아무런 값도 누르지 않았을 땐, 메인 페이지와 동일하게 보여주기
2. 플랫폼은 교집합
3. 장르는 합집합으로 보여주기, 

- [x] 커뮤니티 API 설계
